/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * si-red-backend
 * OpenAPI spec version: 1.0.0
 */
import type { MakeInfo } from './makeInfo';

export interface ModelInfo {
  id: number;
  name: string;
  make: MakeInfo;
}
