/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * si-red-backend
 * OpenAPI spec version: 1.0.0
 */

/**
 * Make all properties in T optional
 */
export interface PartialVehicleInput {
  model_id?: number;
  year?: string;
  vin?: string;
  street?: string;
  city?: string;
  state?: string;
  country?: string;
  zipcode?: string;
  user_id?: string;
  status?: string;
  location?: string;
}
