/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * si-red-backend
 * OpenAPI spec version: 1.0.0
 */

export interface VehicleAttributes {
  id: string;
  model_id: number;
  user_id: string;
  year: string;
  vin: string;
  street: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
  status: string;
  location: string;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
}
