/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * si-red-backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DecodeVinParams,
  VinResponse
} from '.././schemas';

import { customMutator } from '.././customMutator';




export const decodeVin = (
    params: DecodeVinParams,
 signal?: AbortSignal
) => {
      
      
      return customMutator<VinResponse>(
      {url: `/vin`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getDecodeVinQueryKey = (params: DecodeVinParams,) => {
    return [`/vin`, ...(params ? [params]: [])] as const;
    }

    
export const getDecodeVinQueryOptions = <TData = Awaited<ReturnType<typeof decodeVin>>, TError = unknown>(params: DecodeVinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDecodeVinQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof decodeVin>>> = ({ signal }) => decodeVin(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DecodeVinQueryResult = NonNullable<Awaited<ReturnType<typeof decodeVin>>>
export type DecodeVinQueryError = unknown


export function useDecodeVin<TData = Awaited<ReturnType<typeof decodeVin>>, TError = unknown>(
 params: DecodeVinParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof decodeVin>>,
          TError,
          Awaited<ReturnType<typeof decodeVin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecodeVin<TData = Awaited<ReturnType<typeof decodeVin>>, TError = unknown>(
 params: DecodeVinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof decodeVin>>,
          TError,
          Awaited<ReturnType<typeof decodeVin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecodeVin<TData = Awaited<ReturnType<typeof decodeVin>>, TError = unknown>(
 params: DecodeVinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDecodeVin<TData = Awaited<ReturnType<typeof decodeVin>>, TError = unknown>(
 params: DecodeVinParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decodeVin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDecodeVinQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



